### ISSUE TITLE
Secp256k1Net.secp256k1_context_create::Invoke' has unbalanced the stack

### ISSUE THREAD

**Issue by dsemenovsky** [MeadowSuite/Secp256k1.Net#1]
Hi! I'm trying to use your library in a WPF application, but I get the following error:

Secp256k1Net.secp256k1_context_create::Invoke' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'

What should I do to avoid it?

**Comment by zone117x** [comment]
32 or 64 bit?

**Comment by dsemenovsky** [comment]
I think on both. I explicitly set platform to x86 and still have this problem.
![capture](https://user-images.githubusercontent.com/367111/42713132-5bc08f2c-86bc-11e8-96bd-45d3d10d4e27.PNG)

**Comment by dsemenovsky** [comment]
Figured out. Had to disable PInvokeStackImabalance in Managed Debugging Assistant.

**Comment by zone117x** [comment]
Just tested and in 64 bit mode that exception doesn't occur. I'm not sure why its happening for 32bit. Let me know if you run into memory corruption issues.
