### ISSUE TITLE
Support linux-arm64

### ISSUE THREAD

**Issue by ipdae** [MeadowSuite/Secp256k1.Net#12]
Hi, any plans to support linux-arm64?

**Comment by zone117x** [comment]
The nuget package containing the native libs needs updated to bundle linux-arm64, the nuget files are here: https://github.com/MeadowSuite/secp256k1/blob/master/Secp256k1.Native.nuspec#L13

Then, this C# wrapper needs an entry added for linux-arm64 around here https://github.com/MeadowSuite/Secp256k1.Net/blob/master/Secp256k1.Net/LibPathResolver.cs#L22

The code changes are easy. Setting up the CI to build / cross-compile everything, test, and publish to nuget is the tedious part. I think the nuget package with native code was historically done manually.

**Comment by zone117x** [comment]
Tested on ubuntu-21.04 arm64 docker, and also added support for Apple Silicon. Give it a try and let me know if it works for you.

**Comment by ipdae** [comment]
It works. thank you!
