### ISSUE TITLE
Using this on the Stratis Bitcoin node

### ISSUE THREAD

**Issue by dangershony** [MeadowSuite/Secp256k1.Net#3]
I wonder if this is stable enough to use on our fullnode instead of BC
https://github.com/stratisproject/StratisBitcoinFullNode

**Comment by zone117x** [comment]
This wrapper is pretty minimal and I believe there are at least 2 usages of this in production. The native C lib is certainly stable (used by bitcoin and ethereum).

**Comment by dangershony** [comment]
Awesome thanks will give it a try.
