### ISSUE TITLE
Get this pushed directly to sec256 repo

### ISSUE THREAD

**Issue by dangershony** [MeadowSuite/Secp256k1.Net#4]
Did you try to get the C# binding changes pushed to the secp library?
They already have Java binding I think they are open to C#

**Comment by zone117x** [comment]
For the native lib at https://github.com/MeadowSuite/secp256k1/ ?
Most of the changes are for providing a cross platform cmake build script, and exposing the symbols as a shared library. There have been pending pull requests to add a cmake build script for quite some time that they have not accepted. 
https://github.com/bitcoin-core/secp256k1/pull/315
https://github.com/bitcoin-core/secp256k1/pull/549

**Comment by zone117x** [comment]
Any additional thoughts on this?
I'm going to close the issue for now.
