### ISSUE TITLE
PublicKeySerialize and `publicKey` parameter in compressed form

### ISSUE THREAD

**Issue by mixitka** [MeadowSuite/Secp256k1.Net#5]
Hi,

I'm a bit puzzled with the if statement on the following line: https://github.com/MeadowSuite/Secp256k1.Net/blob/master/Secp256k1.Net/Secp256k1.cs#L263 

```C#
if (publicKey.Length < PUBKEY_LENGTH)
{
       throw new ArgumentException($"{nameof(publicKey)} must be {PUBKEY_LENGTH} bytes");
}
```

Shouldn't the if statement look like its corresponding code in https://github.com/bitcoin-core/secp256k1/blob/master/src/secp256k1.c#L193:

```C
ARG_CHECK(*outputlen >= ((flags & SECP256K1_FLAGS_BIT_COMPRESSION) ? 33 : 65));
```
?

Just to explain what I try to accomplish, I try to use `PublicKeySerialize` function with compressed pub key but if I'm not missing something it is not possible at the moment. However, from the C code it looks like it is supported. 

Kind regards,
Martin

**Comment by zone117x** [comment]
The C code referenced is for the output length which looks like it has correct equivalent C# code. However, the C# code performing the input length does look like it doesn't support compressed keys. The equivalent C length check is around here https://github.com/bitcoin-core/secp256k1/blob/master/src/eckey_impl.h#L44

Feel free to submit a PR to fix this!

**Comment by mixitka** [comment]
@zone117x You are right. 

The PR is here https://github.com/MeadowSuite/Secp256k1.Net/pull/6/files Please have a look.

**Comment by zone117x** [comment]
I reviewed the C code a bit more and it appears that the public key input value should always be 64 bytes.

> I try to use PublicKeySerialize function with compressed pub key

I think your usage of the API is actually incorrect. It doesn't appear that the serialize function is designed to take anything but a 64 byte public key, see 
https://github.com/bitcoin-core/secp256k1/blob/e96901a4b951dfb6336114d223151dd0f5ffb89b/include/secp256k1.h#L66
and 
https://github.com/bitcoin-core/secp256k1/blob/master/src/secp256k1.c#L139

**Comment by zone117x** [comment]
What are you trying to do with a compressed public key? Perhaps you need to use this function https://github.com/MeadowSuite/Secp256k1.Net/blob/master/Secp256k1.Net/Secp256k1.cs#L287 ?

**Comment by MartyIX** [comment]
@zone117x Basically I have a compressed pubKey, block hash and signature and I try to verify the signature using your library. So far I was unable to use compressed pubKey, decompressed is fine.

My code is based on https://github.com/MeadowSuite/Meadow/blob/master/src/Meadow.Core/Cryptography/ECDSA/EthereumEcdsaNative.cs#L201

I'll post a sample of my code tonight when I have more time.

Thank you for your investigation!

**Comment by mixitka** [comment]
@zone117x Basically I have a compressed pubKey, block hash and signature and I try to verify the signature.

I'll try to post a sample of my code later tonight when I have more time. (Currently my code is adapted from https://github.com/MeadowSuite/Meadow/blob/master/src/Meadow.Core/Cryptography/ECDSA/EthereumEcdsaNative.cs#L201)

Thank you for your investigation!

**Comment by zone117x** [comment]
It sounds like you'll want to use something more like 
```cs
var serializedPubKey; // your compressed or uncompressed pub key
var parsedPubKey; // variable of where to store the normalized pub key

// parse `serializedPubKey` into `parsedPubKey`
secp256k1.PublicKeyParse(pubKeyOutput, serializedPubKey);
secp256k1.Verify(signature, hash, parsedPubKey);
```

**Comment by MartyIX** [comment]
@zone117x Thank you!

**Comment by mixitka** [comment]
@zone117x Thank you!
