### ISSUE TITLE
secp256k1_ecdsa_signature_parse_der support

### ISSUE THREAD

**Issue by mixitka** [MeadowSuite/Secp256k1.Net#7]
Hi,

would it be possible to add support for `secp256k1_ecdsa_signature_parse_der` function?

Regards,
Martin

**Comment by mixitka** [comment]
https://github.com/MeadowSuite/Secp256k1.Net/pull/8

**Comment by zone117x** [comment]
Updated package with these changes published to nuget https://www.nuget.org/packages/Secp256k1.Net/0.1.54
Thanks for the contribution!
